### ISSUE TITLE
Paimon: token does not exist

### ISSUE THREAD

**Issue by yhuaxing** [wechaty/puppet-supports#149]
Please make sure you have read the [Wechaty Puppet Service: Paimon](https://wechaty.js.org/docs/puppet-services/paimon) from Wechaty Official Website before you continue writting this issue.

## Question

1. 每隔一段时间就会出现address not found target wechaty://api.chatie.io/puppet_paimon_xxxxxxxx: token does not exist问题，一般来说重启服务可行，但是今天 无论如何重启都无效了
2. 你的网站 http://120.55.60.194/无法登录了，我确认账号密码正确，但是报账号密码错误
3. 你的微信根本无法加上，hutusheng-bot：对方账号因涉及违规暂不能被加好友，有没有新的？不然每次问题都要来这里问，效率非常低

**Comment by yhuaxing** [comment]
线上项目挺急的，这边给个有效的联系方式吧，每次找你都好难，我续费了一个季度的，现在账号也登陆不上

**Comment by lmhhhhs** [comment]
我也有一样的问题，密码莫名其妙被改了，token过期时间也改到2021年，token提示不存在

**Comment by yhuaxing** [comment]
怎么石沉大海音信全无了？

**Comment by zpaimon** [comment]
> 每隔一段时间就会出现address not found target wechaty://api.chatie.io/puppet_paimon_xxxxxxxx: token does not exist问题，一般来说重启服务可行，但是今天 无论如何重启都无效了


这个是因为api.chatie.io在国外，确保你的网络环境能够访问这个地址。

@huan

**Comment by zpaimon** [comment]
> 我也有一样的问题，密码莫名其妙被改了，token过期时间也改到2021年，token提示不存在 需要正常使用这个token 麻烦尽快修复一下

你现在还是不能用吗？

**Comment by huan** [comment]
> 这个是因为api.chatie.io在国外，确保你的网络环境能够访问这个地址。

Please feel free to file a report in this repo by creating an issue, to record that your network IP which can not connect to our api.chatie.io

As far as I know today, the service is working fine in China. The worst-case can be resolved after a few retries.

**Comment by yhuaxing** [comment]
> 

并不是，是因为我在他网站注册的账号信息被改了密码变成了123456，而且买的token过期时间被改成了1999-01-01 00:00:00

**Comment by yhuaxing** [comment]
> > 我也有一样的问题，密码莫名其妙被改了，token过期时间也改到2021年，token提示不存在 需要正常使用这个token 麻烦尽快修复一下
> 
> 你现在还是不能用吗？

我的还没有被恢复，密码变成了123456 token过期时间被改成了1999-01-01 00:00:00
我连续买了一个季度的

**Comment by lmhhhhs** [comment]
> > 我也有一样的问题，密码莫名其妙被改了，token过期时间也改到2021年，token提示不存在 需要正常使用这个令牌 麻烦尽快修复一下
> 
> 你现在还是不能用吗？

还是不行，过期时间被改了

**Comment by lmhhhhs** [comment]
给个联系方式

**Comment by zpaimon** [comment]
https://wechaty.js.org/docs/puppet-services/paimon

**Comment by lmhhhhs** [comment]
提供个微信吧

**Comment by zpaimon** [comment]
![image](https://user-images.githubusercontent.com/76138143/167383273-3e6a7690-0a4b-4142-8bd7-8ed200121415.png)

**Comment by yhuaxing** [comment]
> ![image](https://user-images.githubusercontent.com/76138143/167383273-3e6a7690-0a4b-4142-8bd7-8ed200121415.png)

这个反应过好多次了看上面第三条。你的微信根本无法加上，hutusheng-bot：对方账号因涉及违规暂不能被加好友，有没有新的？不然每次问题都要来这里问，效率非常低

**Comment by zpaimon** [comment]
Try again!

**Comment by yhuaxing** [comment]
> Try again!

确实可以了
