### ISSUE TITLE
Paimon: How to detect whether the information contains words that are banned

### ISSUE THREAD

**Issue by kangming06** [wechaty/puppet-supports#152]
## Question
I use an AI chat robot, she sometimes speaks some uncivilized language.
**So I need to check whether this message can be sent smoothly.**
![image](https://user-images.githubusercontent.com/74850890/172667160-a215389e-aacd-48c6-b131-ae0890caf47f.png)

**Comment by zpaimon** [comment]
We use openai@tecent to detect sensitive words.

https://openai.weixin.qq.com/
