### ISSUE TITLE
[FEAT]WorkPro请问可以发送富文本消息吗？

### ISSUE THREAD

**Issue by orsiieyjam** [wechaty/puppet-supports#408]
![image](https://github.com/wechaty/puppet-supports/assets/120195428/28b5b333-3332-42a7-be44-6cac7c5b7270)
发送消息的时候能不能将富文本消息转化呢

**Comment by hcfw007** [comment]
不可以的

**Comment by hcfw007** [comment]
无反馈，问题关闭。
