### ISSUE TITLE
[BUG]WorkPro:启动的时候报错，这是什么原因，导致的呢

### ISSUE THREAD

**Issue by zhaunglengdao** [wechaty/puppet-supports#420]
![image](https://github.com/wechaty/puppet-supports/assets/152667599/0cfadaac-95a9-4675-b920-30c4204b8b04)

**Comment by zhaunglengdao** [comment]
![image](https://github.com/wechaty/puppet-supports/assets/152667599/5023c6ac-c5de-4914-9f5a-f60effdf9add)

**Comment by Pg4O5Q3RiSD5** [comment]
我也遇到同样的报错，之前一直运行良好。也没有更新代码过

**Comment by zhaunglengdao** [comment]
> 我也遇到同样的报错，之前一直运行良好。也没有更新代码过

你清楚是什么原因吗？，过一会咋启动就不报错了

**Comment by Pg4O5Q3RiSD5** [comment]
确实不报错了。这么看来，应该是wechaty的服务器出现问题了

**Comment by su-chang** [comment]
是的，有一台机器出现了故障导致的，目前已经恢复。

**Comment by hcfw007** [comment]
无反馈，问题关闭。
