### ISSUE TITLE
[FEAT]WorkPro:如何才可以公众号

### ISSUE THREAD

**Issue by zhaunglengdao** [wechaty/puppet-supports#421]
![image](https://github.com/wechaty/puppet-supports/assets/152667599/0c2c7b69-4769-4c18-9556-478f5fa11d77)

**Comment by su-chang** [comment]
没理解你的意思，请详细描述问题。

**Comment by 157476PayneGissing** [comment]
> 没理解你的意思，请详细描述问题。
我如果想给好友发送一篇公众号的文章我该如果通过bot发送？

**Comment by hcfw007** [comment]
公众号文章是一种 UrlLink 类型消息，请参阅文档或在代码中根据自动提示尝试。

**Comment by hcfw007** [comment]
无反馈，关闭。
