### ISSUE TITLE
WXWork: Apply for Token

### ISSUE THREAD

**Issue by freecto** [wechaty/puppet-supports#6]
## Wechaty Puppet WXWork

- Repo: <https://github.com/juzibot/wxwork-tester>
- Provider: [Juzi.BOT](https://juzi.bot)
- Support: <https://github.com/juzibot/wxwork-tester/issues>

## Question

Hello, I want to apply a wechaty token.  thanks  a lot.

**Comment by lijiarui** [comment]
Thanks for the application! You can add wechat: `juzibot` and get a wxwork test!
